#!/bin/sh

START=12
STOP=15

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
SERVICE="s4n"
SCRIPT="ser4net-infinite"
x=$(ps | grep -v grep | grep $SCRIPT)

case "$1" in
  start) 
        echo -n "Starting Ser4NET infinite script: $SCRIPT -> $SERVICE ... "
        if [ -n "$x" ]; then
            echo -n "alreadey running, skip"
        else
            /opt/Ser4Net/$SCRIPT &
            #/home/root/bin/$SCRIPT &
        fi
        echo "done."
        ;;

stop) 
    echo -n "Stop existing infinite script"
    x=$(ps | grep -v grep | grep $SCRIPT)
    if [ -n "$x" ]; then
        #get pid
        p=$(echo $x | head -n1 | awk '{print $1;}' )
        kill -9 $p
        killall -9 $SERVICE
    else
        echo -n "... not running, skip"
        y=$(ps | grep -v grep | grep $SERVICE)
            if  [ -n "$y" ]; then
                killall -9 $SERVICE
            fi
        fi
        echo "... done."
        ;;

restart) 
    stop
    sleep 1
    start
;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
