#!/bin/sh
#This is /etc/ini.d/feetsee.sh autostart file

START=12
STOP=15

PATH="/opt/LuckFox/Modem:/sbin:/bin:/usr/sbin:/usr/bin"
echo "PATH=$PATH"
SERVICE="lxmodem"
SCRIPT="lxmodem-infinite"
echo "SERVICE=$SERVICE"
echo "SCRIPT=$SCRIPT"
x=$(ps | grep -v grep | grep $SCRIPT)
echo "x=$x"

case $1 in
    start) 
            echo -n "Starting lxmodem infinite script: $SCRIPT -> $SERVICE ... "
            if [ -n "$x" ]; then
                echo -n "alreadey running, skip"
            else
               # /root/bin/$SCRIPT &
                /opt/Modem/$SERVICE &
                #/home/root/bin/$SCRIPT &
            fi
            echo "done."
            echo "GSM modem START"
    #        /bin/mikro_gsm_ctrl 5
            ;;

    stop) 
            echo -n "Stop existing infinite script"
        x=$(ps | grep -v grep | grep $SCRIPT)
            if [ -n "$x" ]; then
            #get pid
            p=$(echo $x | head -n1 | awk '{print $1;}' )
            kill -9 $p
            killall -9 $SERVICE
        else
            echo -n "... not running, skip"
            y=$(ps | grep -v grep | grep $SERVICE)
                if  [ -n "$y" ]; then
                    killall -9 $SERVICE
                fi
            fi
            echo "... done."
    ;;

    restart)
        stop
        sleep 10
        start
    ;;

esac
